### PR TITLE
Optimized a few features

### PR DESCRIPTION
**Pull request by PossiblePanda**
Hey! I saw that you had a lot of if statements and wanted to help out :) you could go even further by using switch statements but you can do that yourself if you want to. I saw that you are rewriting it soon so hopefully this can help with your rewrite maybe?

If you want me to get rid of the comments let me know :)

### CODE REVIEW

**Review by ccroic — COMMENTED** [review]
Thanks for this optimization!! ^^ i will merge it into this repo!!

**Comment by ccroic** [comment]
github why do you close that 😭😭

**Comment by PossiblePanda** [comment]
> github why do you close that 😭😭

You gotta press the merge button lol

**Comment by ccroic** [comment]
> You gotta press the merge button lol
yeah but i cant open it to merge the pull request, i mark it as open and it forces to being closed

**Comment by PossiblePanda** [comment]
> > You gotta press the merge button lol
> 
> yeah but i cant open it to merge the pull request, i mark it as open and it forces to being closed

oh, strange...

**Pull request closed without merging**
